/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Georg Klein (https://sketchfab.com/kleingeo)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/game-boy-classic-0ae80019e6f046168923286d7e628f6f
Title: Game Boy Classic
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { Float } from '@react-three/drei';


const Gameboy = (props) => {
    const { nodes, materials } = useGLTF('/models/game_boy_classic.glb')
  return (
    <Float
        floatIntensity={2} // Controls the intensity of the floating effect
        rotationIntensity={1} // Controls the intensity of the rotation
        speed={2.2} // Controls the speed of the floating and rotation
      >
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, -6, -2.4]} scale={0.001}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SM_Gameboy_lambert1_0.geometry}
          material={materials.lambert1}
          rotation={[Math.PI / 2, 0, 0]}
        />
      </group>
    </group>
    </Float>
  )
}

useGLTF.preload('/models/game_boy_classic.glb')
export default Gameboy;