/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Phil_XG (https://sketchfab.com/phil_xg)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/fluxs-pit-stop-6bb8bd116e384d9f9e7041dbb84e5e24
Title: Flux's Pit Stop
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { Float } from '@react-three/drei';

const Holo = (props) => {
    const { nodes, materials } = useGLTF('/models/fluxs_pit_stop.glb')
  return (
        <Float
            floatIntensity={2} // Controls the intensity of the floating effect
            rotationIntensity={1} // Controls the intensity of the rotation
            speed={2.2} // Controls the speed of the floating and rotation
          >
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.039}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials.Back}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials.Front}
        />
      </group>
    </group>
    </Float>
  )
}

useGLTF.preload('/models/fluxs_pit_stop.glb')
export default Holo