/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: nyancube (https://sketchfab.com/N01506)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/terrarium-bots-nerdscribbles-bf9a19aae6914a2c866311887edc8b3e
Title: Terrarium Bots (@nerdscribbles)
*/

import React, { useRef } from 'react'
import { useFrame } from '@react-three/fiber';
import { useGLTF } from '@react-three/drei'
import { Float } from '@react-three/drei';

const MiniRobot = props=> {
  const groupRef = useRef(); // Reference to the group

  // Use `useFrame` to rotate the model
  useFrame(() => {
    if (groupRef.current) {
      groupRef.current.rotation.y += .01; // Rotate around Y-axis
    }
  });

  const { nodes, materials } = useGLTF('/models/terrarium_bots_nerdscribbles.glb')
  return (
    <Float
    floatIntensity={1} // Controls the intensity of the floating effect
    rotationIntensity={0.5} // Controls the intensity of the rotation
    speed={2} // Controls the speed of the floating and rotation
  >
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial.geometry}
            material={materials.glass}
            
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_1.geometry}
            material={materials.BOT2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_2.geometry}
            material={materials.BOT1}
          />
        </group>
      </group>
    </group>
    </Float>
  )
}

useGLTF.preload('/models/terrarium_bots_nerdscribbles.glb')
export default MiniRobot;